package com.symplifica.backend.job;

import com.symplifica.backend.entity.NewsLog;
import com.symplifica.backend.repository.NewsLogRepository;
import com.symplifica.backend.service.EmailService;
import com.symplifica.backend.service.LlmService;
import com.symplifica.backend.service.RssService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class NewsJobTest {

    @Mock private RssService rssService;
    @Mock private LlmService llmService;
    @Mock private EmailService emailService;
    @Mock private NewsLogRepository newsLogRepository;

    private NewsJob newsJob;

    @BeforeEach
    void setUp() {
        newsJob = new NewsJob(rssService, llmService, emailService, newsLogRepository);
    }

    @Test
    void shouldExecuteFullWorkflowSuccessfully() {
        List<String> titles = Arrays.asList("Title 1", "Title 2");
        when(rssService.fetchLatestNewsTitles(anyString())).thenReturn(titles);
        when(llmService.summarizeNews(titles)).thenReturn("Summary generated by LLM");
        
        newsJob.executeNewsWorkflow();

        verify(emailService, times(1)).sendNewsSummaryEmail(eq("admin@symplifica.test"), eq("Summary generated by LLM"));
        
        ArgumentCaptor<NewsLog> logCaptor = ArgumentCaptor.forClass(NewsLog.class);
        verify(newsLogRepository, times(1)).save(logCaptor.capture());
        assertEquals("SUCCESS", logCaptor.getValue().getStatus());
    }

    @Test
    void shouldSkipIfNoRssTitles() {
        when(rssService.fetchLatestNewsTitles(anyString())).thenReturn(Collections.emptyList());

        newsJob.executeNewsWorkflow();

        // LLM and Email shouldn't be called
        verify(llmService, never()).summarizeNews(any());
        verify(emailService, never()).sendNewsSummaryEmail(anyString(), anyString());

        ArgumentCaptor<NewsLog> logCaptor = ArgumentCaptor.forClass(NewsLog.class);
        verify(newsLogRepository, times(1)).save(logCaptor.capture());
        assertEquals("SKIPPED", logCaptor.getValue().getStatus());
    }
}
